### ISSUE TITLE
Error after I create a new diagram

### ISSUE THREAD

**Issue by BastienLel** [sharedchains/bpmn-js-modeler-demo#1]
Hi,
I have clone your exemple then install the depedencies with _npm install_. And finally start it with _npm run dev_. But I get an error after I click on "create a new diagram" :

- **No provider for "diagramSwitch"! (Resolving: diagramSwitch)**

Is the exemple still working ?

Thanks in advance

**Comment by snakebyte85** [comment]
Hi BastienLel,

in the README we mentioned this

> For this particular example the version of bpmn-js was modified on our [branch](https://github.com/sharedchains/bpmn-js/tree/feature/multipleDiagram) to add multi-diagram functionalities on bpmn

So the official bpmn-js is incompatible with this demo and you have to build our version of bpmn-js. 

You need to clone this [project](https://github.com/sharedchains/bpmn-js/tree/feature/multipleDiagram), checkout feature/multipleDiagram branch and on the root of that project you must run:
`npm link`

After that, return to the root of this project and run:
`npm link bpmn-js`

This will create a link between the bpmn-js build (with multidiagram support) and the demo project.

Relaunch `npm run all` and try again. Let us know if this worked.

@Ichigo85 I think it's better to insert a note in the README about this

**Comment by BastienLel** [comment]
Hi,
Thanks it work !
I'm trying to build a custom element that open a sub diagram when you for exemple "double click" on them. So I hope your exemple will help me. It's a great start with the multiple diagram support and the possibility to save all of them in the same xml file !

Thanks for your help

**Comment by snakebyte85** [comment]
You're welcome
